from mahjong_question_generator.hand import generate_hands
from mahjong_question_generator.convert import convert_calculator_format, convert_cmajiang_format
from mahjong_question_generator.calculate import calculate
from mahjong_question_generator.generate import generate_question