from mahjong_question_generator.hand import generate_hands
from mahjong_question_generator.convert import convert_calculator_format, convert_cmajiang_format
from mahjong_question_generator.question import hand_to_question
from mahjong_question_generator.generate import generate_question